# Generated by Django 3.2.9 on 2022-01-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
